[project]
name = "gerador-kokoro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "kokoro>=0.9.4",
    "pip>=25.1.1",
    "soundfile>=0.13.1",
    "torch>=2.7.1",
]
